---
output: html_document
runtime: shiny
---
---
title: "Interactive Project"
author: |
  | Nelson
  | Department of Mathematics & Statistics
  | Colby College
date: "5/3/21"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
runtime: shiny


***



# Layouts in Shiny

## Basic layout

We recreate the dataset from the main lecture:

```{r warning=FALSE, message=FALSE}
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(tidyverse)
library(forcats)
library(gridExtra)
library(ggmap)
library(ggthemes)
library(shiny)
library(plotly)
library(httr)
library(maps)
library(egg)
library(grid)
library(stringr)
library(dygraphs)
library(xts)  
library(lubridate)
library(shiny)
library(wordcloud2)
library(tidytext)

terrorism <- read_csv(file = 'globalterrorismdb_0718dist.csv',
                        col_types = cols(
                          iyear = col_integer(),
                          imonth = col_integer(),
                          iday = col_integer(),
                          nkill = col_double(),
                          nwound = col_double()), locale = locale(encoding = "Latin1")
  )
  
  
  
terrorism <- rename(terrorism, c('Year'='iyear','Month'='imonth','Day'='iday','Country'='country_txt','Region'='region_txt','AttackType'='attacktype1_txt','Target'='target1','Killed'='nkill','Wounded'='nwound','Summary'='summary','Group'='gname','Target_Type'='targtype1_txt','Weapon_Type'='weaptype1_txt','Motive'='motive'))
  
dataset <- terrorism

terrorism <- terrorism %>%
  unite(Date, Year, Month, Day, sep = "-", remove = FALSE)
  
```




```{r shinydashboard, warning=FALSE, message=FALSE}
library(shinydashboard)
shinyApp(
  
  ui = dashboardPage(
    dashboardHeader(title = "Revisit the Global Terrorist Situation"),
    
    dashboardSidebar(
    sidebarMenu(
      menuItem("Country Map", tabName = "cm", icon = icon("dashboard")),
      menuItem("Time Series", tabName = "ts", icon = icon("th")),
      menuItem("Motive", tabName = "m", icon = icon("th"))
       )
    ),
    
    dashboardBody(
      tabItems(
      # First tab content
      tabItem(tabName = "cm",
        fluidRow(
          box(
            title = "Select a Country",
            tags$head(tags$script('
                                  var dimension = [0, 0];
                                  $(document).on("shiny:connected", function(e) {
                                      dimension[0] = window.innerWidth;
                                      dimension[1] = window.innerHeight;
                                      Shiny.onInputChange("dimension", dimension);
                                  });
                                  $(window).resize(function(e) {
                                      dimension[0] = window.innerWidth;
                                      dimension[1] = window.innerHeight;
                                      Shiny.onInputChange("dimension", dimension);
                                  });
                              ')),
            selectInput('country_name', 'Country', c(None='.', unique(dataset[c("Country")])), selected = 'Iraq')
          ),
          
          box(
            title = "Map",
            textOutput("is_conf_shown"), 
            plotlyOutput("plot_1")
  
          )
        )
      ),
      # Second tab content
      tabItem(tabName = "ts",
        fluidPage(
            title = "Time Series",
            dygraphOutput("plot_2")
  
          )
      ),
      
      tabItem(tabName = "m",
        fluidPage(
            title = "Motive",
            wordcloud2Output("plot_3", width = "50%", height = "400px")
          )
      )
      )
    )
  ),
  
  server = function(input, output) {
    output$plot_1 <- renderPlotly({
      
      GET("http://httpbin.org/delay/1", timeout(20))
      
      country_cond <- terrorism %>%
        filter(Country == input$country_name)
      
      country_cond$longitude[is.na(country_cond$longitude)] <- 0
      country_cond$latitude[is.na(country_cond$latitude)] <- 0
      
      bounds <- maps::map("world", input$country_name, plot=FALSE)$range
      
      map_bbox <- c(left = bounds[1], bottom = bounds[3], right = bounds[2], top = bounds[4])
      
      map_base <- get_stamenmap(bbox = map_bbox,
                                maptype = "toner-lite",
                                zoom = 6)
      
      name <- paste("Terrorist Situation in",input$country_name, sep=" ")
      
      map_object <- ggmap(ggmap = map_base,
                          extent = "panel") +
        geom_point(data = country_cond, aes(x = longitude, y = latitude, text = paste("Summary: ", gsub('(.{1,20})(\\s|$)', '\\1\n', Summary),
                                                                                      "<br>City: ", city,
                                                                                      "<br>Number of People Killed: ", Killed,
                                                                                      "<br>Motive: ", Motive)), colour = "red", size = 0.2) +
        labs(title = name,
             caption = "Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.") +
        theme_bw()  %+replace%
        theme(text = element_text(family="serif", face="bold", size=12)) +
        theme(axis.title.x=element_blank(), axis.text.x=element_blank(),
              axis.ticks.x=element_blank(),
              axis.title.y=element_blank(), axis.text.y=element_blank(),
              axis.ticks.y=element_blank()) +
        theme(axis.text=element_text(size=13),
              title = element_text(size = 15))
      
      ggplotly(map_object, tooltip = "text")
      
    })
    
    output$plot_2 <- renderDygraph({
      
      country_cond <- terrorism %>%
        filter(Country == input$country_name)
      
      
      name <- paste("Trend of Terrorist Situation in",input$country_name, sep=" ")
      
      
      country_cond <- country_cond %>%
        group_by(Date) %>%
        summarize(count = n())
      
      country_cond$Date <- as.Date(country_cond$Date)
      
      country_cond <- na.omit(country_cond)
      
      don <- xts(x = country_cond$count, order.by = country_cond$Date)
      
      p <- dygraph(don) %>%
        dyOptions(labelsUTC = TRUE, fillGraph=TRUE, fillAlpha=0.1, drawGrid = FALSE, colors="#D8AE5A") %>%
        dyRangeSelector() %>%
        dyCrosshair(direction = "vertical") %>%
        dyHighlight(highlightCircleSize = 5, highlightSeriesBackgroundAlpha = 0.2, hideOnMouseOut = FALSE)  %>%
        dyRoller(rollPeriod = 1)
      
      p
    })
    
    output$plot_3 <- renderWordcloud2({
      country_cond <- terrorism %>%
        filter(Country == input$country_name)
      
      df <- data.frame(column = country_cond$	
targsubtype1_txt)
      
      #column
      #1 Hi my name is Corey!
      #2   Hi my name is John
      
      all_words <- unlist( # flattten word list from individual strings into one vector
        regmatches(df$column,  gregexpr('\\w+', df$column))) # extract all words
      # count frequencies
      freq_count <- table(all_words)
      
      wordcloud2(data = freq_count, size = 0.4, color = "red", shape = "circle")
    })
    
  },
  
  options = list(height = 800)
)
```




